# Copyright (C) 2021 Open Source Integrators
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

import uuid

from markupsafe import Markup

from odoo import api, exceptions, fields, models


class AccountMove(models.Model):
    _inherit = "account.move"

    @api.depends("restrict_mode_hash_table", "state")
    def _compute_show_reset_to_draft_button(self):
        super()._compute_show_reset_to_draft_button()
        # Invoices generated by an external API can't be reset to draft
        self.filtered("external_invoice_id").write(
            {"show_reset_to_draft_button": False}
        )

    @api.depends("move_type", "journal_id.use_invoice_api")
    def _compute_can_invoice_api(self):
        for invoice in self:
            invoice.can_invoice_api = (
                invoice.journal_id.use_invoice_api and invoice.is_sale_document()
            )

    @api.depends("can_invoice_api", "company_id.invoice_api_template_id")
    def _compute_can_invoice_api_email(self):
        for invoice in self:
            invoice.can_invoice_api_email = (
                invoice.can_invoice_api
                and invoice.company_id.invoice_api_template_id
            )

    external_invoice_id = fields.Char(
        "External Invoice ID",
        copy=False,
        index=True,
        readonly=True,
    )
    external_invoice_state = fields.Selection(
        [
            ("draft", "Draft"),
            ("generated", "Generated"),
            ("cancelled", "Cancelled"),
            ("error", "Error"),
        ],
        string="External Invoice State",
        default="draft",
        copy=False,
        readonly=True,
    )
    external_invoice_number = fields.Char(
        "External Invoice Number",
        copy=False,
        readonly=True,
    )
    external_invoice_url = fields.Char(
        "External Invoice URL",
        copy=False,
        readonly=True,
    )
    external_invoice_last_error = fields.Text(
        "External Invoice Last Error",
        copy=False,
        readonly=True,
    )
    can_invoice_api = fields.Boolean(compute="_compute_can_invoice_api")
    can_invoice_api_email = fields.Boolean(compute="_compute_can_invoice_api_email")

    def _get_invoice_api_backend(self):
        self.ensure_one()
        return self.journal_id.invoice_api_backend_id

    def _get_invoice_api_partner(self):
        # Hook to customize the partner/customer used in the API values
        return self.commercial_partner_id

    def _prepare_invoice_api_partner_vals(self, partner):
        self.ensure_one()
        return {
            "name": partner.name or "",
            "external_ref": partner.ref or "",
            "vat": partner.vat or "",
            "address": ", ".join(filter(None, [partner.street, partner.street2])),
            "city": partner.city or "",
            "zip_code": partner.zip or "",
            "country_code": partner.country_id.code or "",
            "country_name": partner.country_id.name or "",
            "email": partner.email or "",
            "phone": partner.phone or "",
            "website": partner.website or "",
            "language": "",
        }

    def _prepare_invoice_api_line_vals(self, line):
        self.ensure_one()
        tax = line.tax_ids[:1]
        return {
            "name": line.product_id.default_code
            or line.product_id.display_name
            or line.name
            or "",
            "description": line.name or "",
            "quantity": line.quantity,
            "unit_price": line.price_unit,
            "discount": line.discount,
            "unit_of_measure": line.product_uom_id.name if line.product_uom_id else "",
            "tax": {
                "name": tax.name or "",
                "amount": tax.amount or 0.0,
                "exemption_reason": "",
            },
        }

    def _prepare_invoice_api_vals(self):
        self.ensure_one()
        if not self.invoice_date or not self.invoice_date_due:
            raise exceptions.UserError(
                self.env._("Please set the invoice date and due date.")
            )
        partner = self._get_invoice_api_partner()
        lines = self.invoice_line_ids.filtered(
            lambda x: x.display_type not in ("line_section", "line_note")
        )
        return {
            "document_type": "invoice",
            "document_date": self.invoice_date,
            "due_date": self.invoice_date_due,
            "reference": self.ref or "",
            "currency": self.currency_id.name or "",
            "exchange_rate": None,
            "partner": self._prepare_invoice_api_partner_vals(partner),
            "lines": [
                self._prepare_invoice_api_line_vals(line) for line in lines
            ],
            "notes": self.narration or "",
            "tax_exemption": "",
            "proprietary_uid": "ODOO" + str(uuid.uuid4()).replace("-", ""),
            "owner_invoice_id": "",
        }

    def action_post_to_external_invoice_api(self):
        for invoice in self.filtered("can_invoice_api"):
            backend = invoice._get_invoice_api_backend()
            if not backend:
                raise exceptions.UserError(
                    self.env._("No invoice API backend configured for this journal.")
                )
            client = backend.get_client()
            vals = invoice._prepare_invoice_api_vals()
            result = client.create_invoice(vals)
            invoice._set_external_invoice_status(result)

    def _set_external_invoice_status(self, result):
        self.ensure_one()
        self.external_invoice_id = result.get("external_id") or ""
        self.external_invoice_number = result.get("number") or ""
        self.external_invoice_url = result.get("url") or ""
        self.external_invoice_state = result.get("state") or "generated"
        self._message_post_external_invoice_created()

    def _message_post_external_invoice_created(self):
        self.ensure_one()
        if self.external_invoice_url:
            link_name = self.env._("View Document")
            link = self.env._(
                "<a class='btn btn-info mr-2' target='new' href=%(link)s>%(name)s</a>",
                link=self.external_invoice_url,
                name=link_name,
            )
            msg = self.env._(
                "External invoice created:"
                "<ul><li>ID: %(external_id)s</li>"
                "<li>%(link)s</li></ul>",
                external_id=self.external_invoice_id,
                link=link,
            )
            self.message_post(body=Markup(msg))
        else:
            msg = self.env._(
                "External invoice created: ID %(external_id)s",
                external_id=self.external_invoice_id,
            )
            self.message_post(body=Markup(msg))

    def _prepare_invoice_api_email_vals(self):
        self.ensure_one()
        template_id = self.company_id.invoice_api_template_id
        if not template_id:
            return None
        values = template_id._generate_template(
            [self.id], ["subject", "body_html", "email_to", "email_cc"]
        )[self.id]
        if not values.get("email_to"):
            return None
        return {
            "message": {
                "client": {"email": values["email_to"], "save": "0"},
                "cc": values["email_cc"],
                "subject": values["subject"],
                "body": values["body_html"],
            }
        }

    def action_send_external_invoice_email(self):
        for invoice in self.filtered("can_invoice_api_email"):
            if not invoice.external_invoice_id:
                raise exceptions.UserError(
                    self.env._(
                        "Invoice %(invoice)s is not registered in the external API yet.",
                        invoice=invoice.name,
                    )
                )
            backend = invoice._get_invoice_api_backend()
            if not backend:
                raise exceptions.UserError(
                    self.env._("No invoice API backend configured for this journal.")
                )
            email_data = invoice._prepare_invoice_api_email_vals()
            if email_data:
                client = backend.get_client()
                client.send_email(invoice.external_invoice_id, email_data)
                msg = self.env._(
                    "External invoice email sent:"
                    "<ul><li>To: %(email)s</li><li>Cc: %(cc)s</li></ul>",
                    email=email_data["message"]["client"]["email"],
                    cc=email_data["message"].get("cc", ""),
                )
                invoice.message_post(body=Markup(msg))

    def _post(self, soft=True):
        res = super()._post(soft=soft)
        for invoice in self:
            if invoice.can_invoice_api and not invoice.external_invoice_id:
                invoice.action_post_to_external_invoice_api()
        return res
